//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellFar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellFar.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;#
        ///.SYNOPSIS
        ///	The internal profile.
        ///	Author: Roman Kuzmin
        ///#&gt;
        ///
        ///# Ignore errors
        ///trap { continue }
        ///
        ///# Hide &apos;more.com&apos;
        ///Set-Alias more.com more
        ///
        ///&lt;#
        ///.SYNOPSIS
        ///	FarNet &apos;Clear-Host&apos;.
        ///#&gt;
        ///function Clear-Host
        ///{
        ///	$Far.UI.Clear()
        ///}
        ///
        ///&lt;#
        ///.SYNOPSIS
        ///	FarNet &apos;more&apos;.
        ///#&gt;
        ///function more
        ///(
        ///	[string[]]$paths
        ///)
        ///{
        ///	if ($paths -and $paths.length -ne 0)  {
        ///		foreach ($file in $paths) {
        ///			Get-Content $file
        ///		}
        ///	}
        ///	else {
        ///		$input
        ///	}
        ///}
        ///
        ///&lt;#
        ///.SYNOPSIS
        ///	Far friendly &apos;Get-History&apos;.
        ///#&gt;
        ///function  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerShellFar {
            get {
                return ResourceManager.GetString("PowerShellFar", resourceCulture);
            }
        }
    }
}
